# Generated by Django 5.0.3 on 2024-03-28 18:11

import accountio.utils
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountio', '0002_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=accountio.utils.get_user_address_slug, unique=True),
        ),
    ]
